name: ros2-galactic-common_test

on:
  push:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/greyltc-org/archlinux-aur:yay
          options: -v ${{ github.workspace }}/ros2-galactic-common:/ros2-galactic-common
          run: bash /ros2-galactic-common/.github/workflows/ros2-galactic-common.bash
